version: "3.6"

# Development environment set up for this application
services:
  # Neo4j graph database for analysis input
  # Note that we use enterprise edition. Please arrange a license when using this commercially.
  neo4j:
    image: neo4j:4.2.6-enterprise
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j:/conf
      - neo4j:/data
      - neo4j:/import
      - neo4j:/logs
      - neo4j:/plugins
    environment:
      # Start with a default database
      - NEO4J_dbms_default__database=thesis
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      # DO NOT copy paste these auth variables for a production environment
      - NEO4J_AUTH=neo4j/local-development-secret

  # PostgreSQL database for analysis configuration
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: thesis
    volumes:
      - postgres:/var/lib/postgresql/data

# Store data of databases between restarts in Docker volume
volumes:
  neo4j:
  postgres:
