version: "3.6"

# Development environment set up for this application
services:
  # Neo4j graph database for storing input and result data
  neo4j:
    image: neo4j:4.3.0
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j:/conf
      - neo4j:/data
      - neo4j:/import
      - neo4j:/logs
      - neo4j:/plugins
    environment:
      # Start with a default database
      - NEO4J_dbms_default__database=tocairn
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      # DO NOT copy paste these auth variables for a production environment
      - NEO4J_AUTH=neo4j/password
      # Allow for DB upgrades
      - NEO4J_dbms_allow__upgrade=true

# Store data of databases between restarts in Docker volume
volumes:
  neo4j:
