spring:
  # Neo4j properties for local development
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: local-development-secret
  data:
    neo4j.database: thesis

  # PostgreSQL properties for local development
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/thesis
    username: postgres
    password: postgres
  jpa:
    open-in-view: false

  # Configuration of ObjectMapper
  jackson:
    default-property-inclusion: non_null