spring:
  # Neo4j properties for local development
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  data:
    neo4j.database: thesis

  # Configuration of ObjectMapper
  jackson:
    default-property-inclusion: non_null