package me.soels.thesis;

/**
 * An objective measures how well a clustering performs in terms of a characteristic of the input data. This defines a
 * dimension into the optimization algorithm which determines a clustering structure relevant to this characteristic.
 * <p>
 * For example, the data autonomy objective would provide a value on the given clustering to indicate how well this
 * clustering is representing data autonomy.
 */
public interface Objective {
    /**
     * Calculate the objective function for the given clustering based on the given application input.
     * <p>
     * The clustering only contains the nodes that are combined together whereas the application input should
     * hold more information needed to determine the resulting objective's value.
     *
     * @param clustering       the decoded clustering as generated by the evolutionary algorithm
     * @param applicationInput the input for the analysis containing the information required for this objective
     *                         function to evaluate
     * @return the resulting measurement for this objective function
     */
    double calculate(Clustering clustering, ApplicationInput applicationInput);
}
